# Generated by Django 4.2.6 on 2024-01-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=255)),
                ('counter', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
